rh_repos:
  - rhel-7-server-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-openstack-11-rpms
  - rhel-ha-for-rhel-7-server-rpms
  

packages:
  - "@Development Tools"
  - git
  - screen
  - mc
  - wget
  - net-tools
  - bind-utils
  - iptables-services
  - bridge-utils 
  - bash-completion 


