# Prepare for Gluster install

# Prepare workstation
- name: prepare workstation
  hosts: ws
  remote_user: vagrant
  become: true

  roles:
  - common
  - register
  - update
  - install
  - { name: ssh_copy_id, remote_ssh_user: ['vagrant', 'root'] }


  tasks:
  - name: Update MOTD
    blockinfile: 
      block: "Host prepared"
      insertafter: EOF
      marker: "==============================================================="
      dest: /etc/motd

- name: prepare gluster nodes
  hosts: gluster
  remote_user: vagrant
  become: true

  handlers:
  - name: restart NetworkManager
    service: name=NetworkManager state=restarted


  pre_tasks:
  - name: modify network manager config
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      section: main
      option: dns
      value: none
    notify: "restart NetworkManager"
  - name: fix resolv.conf
    copy:
      content: |
        search lab
        nameserver 192.168.121.1
      dest: /etc/resolv.conf

   

  roles:
  - common
  - register
  - update
  - install

  tasks:
  - name: Update /etc/hosts from inventory
    lineinfile: 
      dest: /etc/hosts
      regexp: '.*{{item}}$' 
      line: '{{hostvars[item].ansible_default_ipv4.address}} {{item}}' 
      state: present
    with_items: '{{groups.all}}'

  - name: Start gluster service
    service: 
      name: glusterd
      state: started
      enabled: true
  - name: Update MOTD
    blockinfile: 
      block: "gluster prepared"
      insertafter: EOF
      marker: "==============================================================="
      dest: /etc/motd

      
