# Prepare for Gluster install

# Prepare workstation

- name: prepare gluster nodes
  hosts: gluster
  remote_user: vagrant
  become: true

  roles:
  - common-rhel
  - register
  - update
  - install

  tasks:
  - name: Update /etc/hosts from inventory
    lineinfile: 
      dest: /etc/hosts
      regexp: '.*{{item}}$' 
      line: '{{hostvars[item].ansible_default_ipv4.address}} {{item}}' 
      state: present
    with_items: '{{groups.all}}'

  - name: Start gluster service
    service: 
      name: glusterd
      state: started
      enabled: true
  - name: Update MOTD
    blockinfile: 
      block: "gluster prepared"
      insertafter: EOF
      marker: "==============================================================="
      dest: /etc/motd
  - name: Create Topology 
    template:
      src: work/topology.j2
      dest: work/topology.json 
    delegate_to: localhost
    run_once: true

      
