# Prepare for Openshift install

# Prepare workstation

- name: prepare openshift install workstation
  hosts: workstation
  remote_user: vagrant
  become: true

  roles:
  - common-rhel
  - register
  - update
  - install

  tasks:
  - name: Update MOTD
    blockinfile: block="Openshift prepared"
                 insertafter=EOF
                 marker="==============================================================="
                 dest=/etc/motd

