# Prepare for Openshift install

# Prepare workstation

- name: prepare openshift install workstation
  hosts: workstation
  remote_user: vagrant
  become: true

  roles:
  - common
  - register
  - update
  - install
  - ssh_copy_id

  tasks:
  - name: Update MOTD
    blockinfile: block="Openshift prepared"
                 insertafter=EOF
                 marker="==============================================================="
                 dest=/etc/motd

# Prepare nodes.

- name: Prepare nodes
  hosts: masters,nodes,storage,infra
  remote_user: vagrant
  become: true
  
  roles:
  - common
  - register
  - update
  - install

# Add ip/hostnames to storagehosts

- name: fill /etc/hosts
  hosts: storage
  remote_user: vagrant
  become: true
  
  tasks:
  - name: Update /etc/hosts from inventory
    lineinfile: 
      dest: /etc/hosts 
      regexp: '.*{{item}}$' 
      line: '{{hostvars[item].ansible_default_ipv4.address}} {{item}} {{hostvars[item].ansible_fqdn}}' 
      state: present
    with_items: '{{groups.storage}}'


# Create topology.json
# Note: "work" is synched between the local host and the virtual workstation by Vagrant

- name: create topology.json
  hosts: workstation
  remote_user: vagrant
  become: true

  tasks:
  - template:
      src: work/topology.j2
      dest: work/topology.json 
  
