- stat: path=/etc/pki/consumer/cert.pem
  register: registered


- name: Register the box with the Red Hat Portal
  redhat_subscription:
    state: present
    username: "{{ rh_username }}"
    password: "{{ rh_password }}"
    pool: "{{ rh_pool }}"
    server_hostname: "{{ rh_server }}"
    server_insecure: "{{ rh_insecure }}"
    autosubscribe: false
  when: registered.stat.exists == false
  retries: 3
  delay: 3
  register: result
  until: result | success

- name: Set Repositories we need.
  shell: |-
     subscription-manager repos --disable '*'{{ ' ' }}
     {%- for repo in rh_repos -%}
       --enable {{ repo | quote }}{{ ' ' }}
     {%-  endfor %}
  retries: 3
  delay: 3
  register: result
  until: result | success

- name: pin the release
  shell: subscription-manager release --set={{ rh_release }}
  when: rh_release is defined

- name: Update MOTD
  blockinfile: 
    insertafter: EOF
    marker: "==============================================================="
    dest: /etc/motd
    content: |
      Registered with Red Hat CDN
      Repositories enabled:
      {{ rh_repos | to_nice_yaml }}

