- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ packages }}"
  retries: 3
  delay: 3
  register: result
  until: result | success


- name: Update MOTD
  blockinfile: 
    insertafter: EOF
    marker: "==============================================================="
    dest: /etc/motd
    content: |
      Packages installed:
      {{ packages | to_nice_yaml }}
                  
